In [3]:
a = [[123,123,123,12345,123456],[123,123,123,12345,123456],[123,123,123,12345,123456]]


In [4]:
a[0]

[123, 123, 123, 12345, 123456]

In [6]:
a[0][0]

123

In [7]:
import numpy
n = numpy.arange(27)

In [10]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [27]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [28]:
n.reshape(3,9)[0][:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [16]:
_3Darray = n.reshape(3,3,3)

In [17]:
print(_3Darray)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [18]:
_3Darray[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
_3Darray[1]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [20]:
_3Darray[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [21]:
_3Darray[0][0]

array([0, 1, 2])

In [22]:
_3Darray[0][2]

array([6, 7, 8])

In [23]:
_3Darray[0][1]

array([3, 4, 5])

In [24]:
_3Darray[0][0][0]

0

In [25]:
_3Darray[0][0][1]

1

In [29]:
m = numpy.asarray( [[123,123,123,12345,123456],[],[]])
print(m)

[list([123, 123, 123, 12345, 123456]) list([]) list([])]


In [30]:
m[0]


[123, 123, 123, 12345, 123456]

In [31]:
m[1]

[]

In [34]:
m[2]

[]

In [67]:
import cv2


In [70]:
img = cv2.imread("smallgray.png",0)


In [72]:
img


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [73]:
cv2.imwrite("newsmallgray.png",img)

True

In [75]:
img.shape


(3, 5)

In [78]:
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [80]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [83]:
ims=numpy.hstack((img,img))
ims


array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [92]:
ims=numpy.vstack((img,img,img))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [95]:
split=numpy.vsplit(ims,3)
split

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]